web:
    image: nginx:latest
    ports:
        - "8080:8080"
    volumes:
        - ./:/www
        - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
        - php

php:
    image: php:7-fpm
    volumes:
        - ./:/www
